---
version: "3.9"
services:
  mycron:
    container_name: mycron
    image: docker.io/sushibox/mycron:latest
    restart: unless-stopped
    environment:
#      - DOCKER_HOST=tcp://dockerproxy:2375
      - ENV_FILE=${ENVFILE}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  hello-world:
    container_name: hello-world
    image: hello-world
    restart: always
    labels:
      - "mycron.enabled=true"
      - "mycron.job-1-hello-world.schedule=*/2 * * * *"
      - "mycron.job-1-hello-world.command=echo 'Hello World Job 1'"
